### ISSUE TITLE
API bug on instagram

### ISSUE THREAD

**Issue by dimitry-gosselin** [GeonetSolutions/laravel-socialwall#1]
Hello,

Great work, for your package.

I began to use it for a business project.

I notice a bug when you parse the instagram API information. When there is no caption associted with user pictures the process bug.

It's better to verify all the instragram parameters before use it.

                        //Ugly quick fix
                        if(!empty($photo->caption)){
                            $photos[$index]['message']              = $photo->caption->text;
                        }else{
                            $photos[$index]['message']              = "";
                        }

**Comment by ollywarren** [comment]
Hi @dimitry-gosselin,

Thanks for using the package and the bug report. we'll take a look into this ASAP. Feel free to send PR if you have a workable fix.

;)

**Comment by lewisthompson93** [comment]
Hi @dimitry-gosselin,

We've fixed the issue for you, please have a look and let us know if you have anymore problems! 👍
